[package]
name = "erc1155-user-mock-meta"
version = "0.0.0"
authors = ["Dorin Iancu <dorin.iancu@dharitri.com>"]
edition = "2021"
publish = false

[dependencies.erc1155-user-mock]
path = ".."

[dependencies.dharitri-wasm-debug]
version = "0.38.0"
path = "../../../../../dharitri-wasm-debug"
