[package]
name = "formatted-message-features-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = [ "you",]

[dev-dependencies]

[dependencies.formatted-message-features]
path = ".."

[dependencies.dharitri-wasm-debug]
version = "0.38.0"
path = "../../../../dharitri-wasm-debug"
