[package]
name = "lottery-erc20"
version = "0.0.0"
authors = [ "Dorin Iancu <dorin.iancu@dharitri.com>",]
edition = "2021"
publish = false

[lib]
path = "src/lottery.rs"

[dependencies.erc20]
path = "../erc20"

[dependencies.dharitri-wasm]
version = "0.38.0"
path = "../../../../dharitri-wasm"
features = ["alloc"]

[dependencies.dharitri-wasm-node]
version = "0.38.0"
path = "../../../../dharitri-wasm-node"
optional = true

[dev-dependencies.dharitri-wasm-debug]
version = "0.38.0"
path = "../../../../dharitri-wasm-debug"
