[package]
name = "fractional-nfts-meta"
version = "0.0.0"
authors = ["Claudiu-Marcel Bruda <claudiu.bruda@dharitri.com>"]
edition = "2021"
publish = false

[dependencies.fractional-nfts]
path = ".."

[dependencies.dharitri-wasm-debug]
version = "0.38.0"
path = "../../../../dharitri-wasm-debug"
