[package]
name = "rust-testing-framework-tester"
version = "0.0.0"
authors = ["Dorin Iancu <dorin.iancu@dharitri.com>"]
edition = "2021"
publish = false

[dependencies.dharitri-wasm]
version = "0.38.0"
path = "../../../dharitri-wasm"
features = [ "alloc" ]

[dependencies.adder]
path = "../../examples/adder"

[dependencies.basic-features]
path = "../../feature-tests/basic-features"

[dev-dependencies.dharitri-wasm-debug]
version = "0.38.0"
path = "../../../dharitri-wasm-debug"

[dev-dependencies]
num-bigint = "0.4.2"
num-traits = "0.2"
hex = "0.4"

[dev-dependencies.forwarder]
path = "../composability/forwarder"

[dev-dependencies.vault]
path = "../composability/vault"
