[package]
name = "token-release-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dev-dependencies]

[dependencies.token-release]
path = ".."

[dependencies.dharitri-wasm-debug]
version = "0.38.0"
path = "../../../../dharitri-wasm-debug"

