[package]
name = "random"
version = "0.0.0"
authors = [ "dorin-iancu <dorin.iancu@dharitri.com>",]
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies.dharitri-wasm]
version = "0.38.0"
path = "../../../../../dharitri-wasm"
