[package]
name = "crowdfunding-erc20"
version = "0.0.0"
authors = ["Dorin Iancu <dorin.iancu@dharitri.com>"]
edition = "2021"
publish = false

[lib]
path = "src/crowdfunding_erc20.rs"

[dependencies.erc20]
path = "../erc20"

[dependencies.dharitri-wasm]
version = "0.38.0"
path = "../../../../dharitri-wasm"

[dev-dependencies.dharitri-wasm-debug]
version = "0.38.0"
path = "../../../../dharitri-wasm-debug"

