[package]
name = "proxy-pause-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = [ "you",]

[dev-dependencies]

[dependencies.proxy-pause]
path = ".."

[dependencies.dharitri-wasm-debug]
version = "0.38.0"
path = "../../../../dharitri-wasm-debug"
