[package]
name = "big-float-features-meta"
version = "0.0.0"
authors = ["Andrei Marinica <andrei.marinica@dharitri.com>"]
edition = "2021"
publish = false

[dependencies.big-float-features]
path = ".."

[dependencies.dharitri-wasm-debug]
version = "0.38.0"
path = "../../../../dharitri-wasm-debug"
