[package]
name = "format-tests"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "format-tests"
path = "src/format_tests.rs"

[dependencies.dharitri-wasm]
version = "0.38.0"
path = "../../../dharitri-wasm"

[dependencies.dharitri-wasm-debug]
version = "0.38.0"
path = "../../../dharitri-wasm-debug"

[dev-dependencies]
glob = "0.3.0"
home = "0.5.3"

[workspace]
members = ["."]
